### ISSUE TITLE
Requirements.txt conflict

### ISSUE THREAD

**Issue by lolmc** [calvinckfong/llama2-langchain#1]
Hi, I wanted to try your guide, but when I tried to install what is in the requirements.txt, it came up with the following conflict. I am installing into a fresh conda environment using Python v3.11.

INFO: pip is looking at multiple versions of kubernetes to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 54) and urllib3==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==2.1.0
    kubernetes 28.1.0 depends on urllib3<2.0 and >=1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by calvinckfong** [comment]
Thank you very much for your feedback.  
The package version for urllib has been loosen.
